### ISSUE TITLE
Get Atum Context, by getting existing partitioning from DB - retrieve Measures and AdditionalData for a given partitioning

### ISSUE THREAD

**Issue by lsulak** [AbsaOSS/atum-service#120]
## Background
It's needed that the endpoint returns actual data.

## Feature
What the ticket says, see the endpoint related to create partitioning event.

## Proposed Solution [Optional]
Solution Ideas:
1. Create _Fa-DB_ classes for `runs.get_partitioning_measures` and `runs.get_partitioning_additional_data` DB functions
2. Call them in `PartitioningController` (`PartitioningController.createPartitioningIfNotExists`)

Depends on #169

**Comment by benedeki** [comment]
This item depends on:
* AbsaOSS/atum-service#169
By **[Dependent Issues](https://github.com/z0al/dependent-issues)**.

**Comment by benedeki** [comment]
This item depends on:
* ~~AbsaOSS/atum-service#169~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)**.
