### ISSUE TITLE
Use Circe as serde library for JSON in Agent, Server and Model modules

### ISSUE THREAD

**Issue by salamonpavel** [AbsaOSS/atum-service#200]
We have decided to use Circe in our projects (Atum, AUL). It's about time to replace the existing serialization with Circe based one.

**Comment by lsulak** [comment]
Perhaps as part of this effort, it might make sense to:
* adopt Atum Agent so that it's perfectly compatible with newly implemented envelopes in #199 in all the versions
* perhaps move the envelope related code to `model/` ❓ just a suggestion

**Comment by lsulak** [comment]
also please test / check if this is still a bug once you have your solution there: https://github.com/AbsaOSS/atum-service/issues/133
