### ISSUE TITLE
Release and Deploy 0.3.0

### ISSUE THREAD

**Issue by lsulak** [AbsaOSS/atum-service#213]
## Background
We need to deploy the Atum server, and this might mean that we'll have to revisit our docker & configuration in our private repo that deployts it into our cloud & on-prem space.

Also, test if Agent is fully compatible with the server.

Depends on: https://github.com/AbsaOSS/atum-service/issues/176
Depends on: https://github.com/AbsaOSS/atum-service/issues/219
Depends on: https://github.com/absa-group/atum-service-deployment/issues/25
Relates to: https://github.com/absa-group/atum-service-deployment/issues/29

**Comment by benedeki** [comment]
Covered by https://github.com/AbsaOSS/atum-service/issues/257 and https://github.com/absa-group/atum-service-deployment/issues/32
