### ISSUE TITLE
Create class for segmentation handling in agent

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#25]
## Background
When working with Atum data the _Segmentation_ information has to be held and provided to the Atum routines.

## Feature
Create a class which will hold the segmentation data and related setup.
The class then can either provide the Atum routines itself or work in tandem with an implicit class to `DataFrame` as an implicit parameter to the routines.

Expected basic functions:
* Create a construtor with a map of `Segmentation field name` -> `value of the segmentation`
* Have a constructor that create a new segmentation by providing additional pair(s) of _Segmentation_ names and values - a sub-segmentation.

## Proposed Solution
Class name Ideas:
1. `AtumSegmentation` or `AtumSegmentationContext` in case of implementation with implicits
2. `AtumAgent` in case of one class implementation

**Comment by seldon851** [comment]
Pull req: https://github.com/AbsaOSS/atum-service/pull/45/files
