### ISSUE TITLE
Create repository with deployment variables

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#47]
## Background
Enable easy deployment of the service

## Feature
Create repository with deployment variables

**Comment by lsulak** [comment]
JFYI the repository has been created here: https://github.com/absa-group/atum-service-deployment

And we have another task for service deployment: #46. One more thing is remaining though before I close this ticket, and that is a self-hosted GH Runner for CICD. I asked Harry to do this and provided some basic instructions.

**Comment by lsulak** [comment]
JFYI the self hosted runner is implemented here: https://github.com/absa-group/atum-service-deployment/pull/3
