### ISSUE TITLE
Create (adjust) endpoint for accepting and saving checkpoint data

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#50]
## Background
The REST API endpoints of the Server

## Feature
Create (or adjust if already exists) API endpoint accepting whole checkpoint data from the Atum agent and saving it to the DB.

## To consider
Some versioning support of the incoming data (agent and server not being of the same release).

Depends on #37

**Comment by benedeki** [comment]
This item depends on:
* AbsaOSS/atum-service#37
By **[Dependent Issues](https://github.com/z0al/dependent-issues)**.

**Comment by benedeki** [comment]
This item depends on:
* AbsaOSS/atum-service#37
By **[Dependent Issues](https://github.com/z0al/dependent-issues)**.

**Comment by lsulak** [comment]
@benedeki is this not dependent also on #48 ?

**Comment by benedeki** [comment]
This item depends on:
* ~~AbsaOSS/atum-service#37~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)**.

**Comment by benedeki** [comment]
Endpoint in symbolic form (naming possible to change):
**`createCheckpoint`/`saveCheckpoint`**
* POST
* IN `CheckpointDTO`
* 
Probably ``save...` name is better.
