### ISSUE TITLE
Add the ability to create a sub-partition

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#61]
## Background
Partitions can be split further and measurements should reflect that.

## Feature
Add the ability to create a sub-partition of a partition. The associated `AtumContext` is then copied into the new `AtumContext` associated with the sub-partition.
(Sub-partition is the same partition as the parent, just with at least one extra key->value pair at the end)

Depends on #25

**Comment by benedeki** [comment]
This item depends on:
* AbsaOSS/atum-service#25
By **[Dependent Issues](https://github.com/z0al/dependent-issues)**.

**Comment by benedeki** [comment]
This item depends on:
* AbsaOSS/atum-service#25
By **[Dependent Issues](https://github.com/z0al/dependent-issues)**.

**Comment by benedeki** [comment]
This item depends on:
* ~~AbsaOSS/atum-service#25~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)**.

**Comment by benedeki** [comment]
This item depends on:
* ~~AbsaOSS/atum-service#25~~
By **[Dependent Issues](https://github.com/z0al/dependent-issues)**.

**Comment by lsulak** [comment]
done, closing
