### ISSUE TITLE
Can Additional data be modified?

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#80]
## Question
Can additional data that already have a value (not `NULL`/`None`be modified?
If yes, they probably should have historization.
If no, what happens if update is tried?

**Comment by lsulak** [comment]
Very good question, happy to talk about it on a call if needed. 

But on the first glance it looks like additional data potentially can contain various things and maybe even some business logic can be applied to it, which might mean that having a history of it can bring some value, i.e. won't limit anybody (unlike no history, just raw updates). 

So I would be inclined to say this: yes they can be modified, but using 'immutability' principle. A brand new record would be created, retiring an old one.

**Comment by lsulak** [comment]
Implemented as part of #58 in #143
